---
# CentOS tasks file for ansible-zabbix-repo
- name: Add zabbix {{ zabbix_version }} repository
  yum_repository:
    name: zabbix
    file: zabbix
    description: Zabbix Official Repository
    baseurl: "{{ zabbix_repo.url }}"
    gpgkey: "{{ zabbix_repo.key[zabbix_version] }}"
    gpgcheck: yes

- name: Add zabbix {{ zabbix_version }} non-supported repository
  yum_repository:
    name: zabbix-non-supported
    file: zabbix
    description: Zabbix Official Repository non-supported
    baseurl: "{{ zabbix_repo.ns_url }}"
    gpgkey: "{{ zabbix_repo.ns_key }}"
    gpgcheck: yes
