---
# tasks file for ansible-zabbix-repo
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Include OS-specific install tasks
  include: "{{ ansible_distribution }}.yml"
