---
# Ubuntu tasks file for ansible-zabbix-repo
- name: Install zabbix apt key
  apt_key:
    url: "{{ zabbix_repo.key_url }}"
    keyring: "{{ zabbix_repo.keyring_path }}"

- name: Add zabbix {{ zabbix_version }} repository
  apt_repository:
    filename: zabbix
    repo: "{{ zabbix_repo.url }}"
    update_cache: yes

- name: Add zabbix {{ zabbix_version }} src repository
  apt_repository:
    filename: zabbix
    repo: "{{ zabbix_repo.src_url }}"
    update_cache: yes
